id = "ragdoll"
title = "Ragdoll Madness"
channel = "Hobby Projects"
date = "4 years ago"
description = """
As part of a 24h high school hackathon, I made a physics
based obstacle course game. You play as a ragdoll, but really
you're the jetpack, grappling hook, and explosion throwing this
poor yellow ragdoll around.

It's made in Unity with 3D assets modeled in Blender and UI
components in Photoshop; everything is done in 24h!
"""
video = "assets/videos/previews/ragdoll.mp4"
tags = ["Unity", "Blender"]
filters = ["All", "Games", "3D Models"]