id = "xwing"
title = "Multiplayer Dogfight Game"
channel = "Hobby Projects"
date = "4 years ago"
description = """
I played Star Wars Battlefront for far too many hours, and wanted to
amplify the arcade-feel of the spaceship dogfight mode.
\n\n
In this project I've made a spaceship controller that's really
satisfying to watch, and even more to play. Then: multiplayer. Using
Unity I added online multiplayer to chase around my friends and shoot
them down.
"""
video = "assets/videos/content/xwing.mp4"
tags = ["C#", "Unity"]
filters = ["All", "Games"]