id = "drone"
title = "RP2040 Drone"
channel = "Hobby Projects"
date = "1 year ago"
description = """
After a professor told me I couldn't, I did: a drone made completely¹ from
scratch using the RP2040 microcontroller, a handful of brushed DC motors
with the MOSFETs to match, and a custom 3D printed frame.
\n\n
So far, the circuit "board" is manually soldered on a perfboard and consists
of the RP2040 with 5 peripherals: one begin the MPU6050 IMU, the other four
are transistors to power the motors(they operate at ~3.7V which the board
can technically handle, but the current draw is far too high so they must
draw straight from the LiPo).
\n\n
In the future I hope to design a custom PCB and finish the flight firware;
note that this is a work-in-progress. So far, I've achieved liftoff(albeit
uncontrollably) and a 2D drone proof-of-concept(it's a balance that stays
at any given angle using two propellers and a PID controller) but there's
much work to be done.
\n\n
¹If you wish to make an apple pie from scratch, you must first invent the
universe
"""
video = "assets/videos/previews/drone.mp4"