id = "lamp"
title = "ESP-32 Lamp"
channel = "MIT Projects"
date = "1 year ago"
description = """
After smart coffee machines and smart fridges, the next
logical progression is smart lamps. This ESP32-based lamp
regularly queries a Flask server that allows the user to
set its RGB color using a web UI.
\n\n
It's definitely one of the simpler projects on this portfolio
(made in one evening), but was the last homework project for
my embedded systems class and features many of the C++ hardware
abstractions I made over the course of the semester.
"""
video = "assets/videos/previews/lamp.mp4"