id = "raytracer"
title = "CPU Raytracer"
channel = "Hobby Projects"
date = "4 years ago"
description = """
One of the first projects I made while learning the Rust
programming language is a CPU raytracer. It's fully parallelized
and supports basic geometry as well as HDRIs.
"""
video = "assets/videos/previews/raytracer.mp4"
tags = ["Rust"]