id = "tft"
title = "RP2040 TFT Drivers"
channel = "Hobby Projects"
date = "1 year ago"
description = """
This project is twofold, and part of something larger(🤫).
\n\n
The first thing is super fast LCD display drivers for a
RP2040 microcontroller; using the typical 1-bit SPI interface,
a moderate screen-size can refresh in 9ms at best. This is
a huge problem, since the CPU is blocked during that time!
\n
The solution: using DMA drivers, all this work can happen in the
background and block the CPU for no more than a few nanoseconds.
\n\n
The second thing is a deferred formatting library for logging
from a microcontroller. By default, a function like `printf` will
do all the work on the microcontroller and take forever, all the
while bloating our binary.
\n
This library instead sends the address
of the format string, the arguments as-is, and lets the host
laptop do the work.
"""
video = "assets/videos/previews/tft.mp4"